# Goal
manymove_msgs/MoveManipulatorGoal plan_request
trajectory_msgs/JointTrajectory existing_trajectory

---
# Result
bool success
string message
int32 error_code    # 0 = success, 1 = aborted, 2 = canceled, 3 = collision
trajectory_msgs/JointTrajectory final_trajectory

---
# Feedback
float32 progress
bool in_collision
